baseURL = "https://cesium.github.io/fractal-tree"
title = "Fractal Tree • CeSIUM"

# Directories
publishDir = "public"

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true
pygmentsStyle = "emacs"

[params.info]
description = "Introductory programming sessions @ University of Minho"
title404 = "Nothing's here!"

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "|"

[blackfriday]
hrefTargetBlank = true
